### PR TITLE
Add Dictionary

### PR DESCRIPTION
**Pull request by claudey**
- Using the `terms` scaffold to handle this task.
- Will link each section to a button
- If the section has entries, both section header and entries will be shown
- If the section has no entries, only the section header will be shown.

https://github.com/maybe-finance/marketing/assets/1866816/4628b307-eebb-4289-a141-2b0bbf1ca82f

/claim #11

### CODE REVIEW

**Comment by claudey** [comment]
- Added dictionary detail page
- Load random terms when page reloads.

https://github.com/maybe-finance/marketing/assets/1866816/df90e596-2e32-4867-81f0-bec0a731b060

**Comment by claudey** [comment]
- Added search handling
- Search is currently implemented under the Terms controller.
- If results are blank, empty results page shows.

https://github.com/maybe-finance/marketing/assets/1866816/831ec10a-7ee8-4886-b5c8-afc6d7d01e6b

**Comment by Shpigford** [comment]
Thanks for the work on this! Opted to go for #13 on this as it was the first completed and their solution was clean and succinct. Going to close this PR for now.

**Comment by claudey** [comment]
Thanks, Josh!

**Pull request closed without merging**
