### PR TITLE
feat: home affordibility calculator

### LINKED ISSUE #60: Build Home Affordability Calculator
Home Affordability

## Feature Overview
This issue is for our "Home Affordability Calculator" which calculates a spectrum of home affordability. This will be added as a [free mini-tool on Maybe](https://maybe.co/tools).

## Requirements
- [ ] Match design elements
- [ ] Loan duration is a drop-down with two options: 15 years, 30 years
- [ ] Loan interest rate should be pre-filled automatically from FRED API
- [ ] Use 0.65% of home value per year for insurance
- [ ] Use 0.90% of home value per year for taxes
- [ ] Empty state

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools
Relevant Stimulus/Javascript code: https://github.com/maybe-finance/marketing/tree/main/app/javascript/controllers

### The FRED API is free and gives US averages for current mortgage rates.
Get a free FRED API key here: https://fred.stlouisfed.org

30-year rate endpoint: https://api.stlouisfed.org/fred/series/observations?series_id=MORTGAGE30US&api_key=YOUR_API_KEY&file_type=json&limit=1&sort_order=desc&frequency=w
15-year rate endpoint: https://api.stlouisfed.org/fred/series/observations?series_id=MORTGAGE15US&api_key=YOUR_API_KEY&file_type=json&limit=1&sort_order=desc&frequency=w

These rates should be cached daily using Rails caching conventions (we use Redis in production for these types of caches, FWIW).

### Rough-draft javascript calculation
Here is some javascript from when we were internally playing around with building this. It won't work exactly for you, but it should give you some color into _how_ to calculate the outcomes.

```
function calculatePresentValue(payment, interestRate, periods) {
    if (interestRate === 0) {
        return payment * periods;
    } else {
        return payment * (1 - Math.pow(1 + interestRate, -periods)) / interestRate;
    }
}

// User inputs
const targetHomePrice = 525000;
const annualIncome = 250000;
const otherMonthlyDebtPayments = 400;
const downPayment = 105000;
const loanTermYears = 30;
const loanInterestRate = .07;
let annualPropertyInsurance = 3000; // see requirement about using a % instead
let annualPropertyTaxes = 2500;  // see requirement about using a % instead
const otherMonthlyCosts = 100; // this is that HOA + PMI field

// Base DTI values
const baseDTI = [0.2, 0.28, 0.36, 0.44];

// Step 2 - Calculations
const annualizedOtherMonthlyDebtPayments = (otherMonthlyDebtPayments * 12) / annualIncome;
const propertyInsurancePercent = annualPropertyInsurance / targetHomePrice;
const propertyTaxesPercent = annualPropertyTaxes / targetHomePrice;

// Step 3 - Determine Multiplier
let multiplier = 1;
if (annualizedOtherMonthlyDebtPayments > 0.08) {
    multiplier = (0.36 - annualizedOtherMonthlyDebtPayments) / 0.28;
}

// Step 4 - Multiply Base DTI by Multiplier
const adjustedDTI = baseDTI.map(dti => dti * multiplier);

// Step 5 - Calculate Monthly Payment using Adjusted DTI
const monthlyIncome = annualIncome / 12;
const monthlyPayment = adjustedDTI.map(dti => (dti * annualIncome) / 12);

// Step 6 - Calculate Base PV
const periods = loanTermYears * 12;
const basePV = monthlyPayment.map(payment => calculatePresentValue(payment, loanInterestRate / 12, periods));

// Step 7 - Add Down Payment to Base PV
const basePVWithDownPayment = basePV.map(pv => pv + downPayment);

// Step 8 - Calculate Monthly Insurance and Tax Costs
const monthlyInsuranceTaxCosts = basePVWithDownPayment.map(pv => pv * (propertyInsurancePercent + propertyTaxesPercent) / 12);

// Step 9 - Subtract Monthly Insurance, Taxes, and Other from Payment
const adjustedMonthlyPayment = monthlyPayment.map((payment, index) => payment - monthlyInsuranceTaxCosts[index] - otherMonthlyCosts);

// Step 10 - Calculate PV based on Adjusted Payment
const adjustedPV = adjustedMonthlyPayment.map(payment => calculatePresentValue(payment, loanInterestRate / 12, periods));

// Step 11 - Add Down Payment to Calculated PV
const adjustedPVWithDownPayment = adjustedPV.map(pv => pv + downPayment);

bubble_fn_val({
    output1: adjustedPVWithDownPayment[0],
    output2: adjustedPVWithDownPayment[1],
    output3: adjustedPVWithDownPayment[2],
    output4: adjustedPVWithDownPayment[3]
});
```

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Home Affordability Calculator Figma Frame](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5870-2335&m=dev)

## Bounty
There is a $300 bounty on this.

To participate in the bounty:

1. Comment `/attempt #60` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #60` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### PR DESCRIPTION
**Pull request by neo773**
https://github.com/maybe-finance/marketing/assets/62795688/9194c023-d998-43a6-a828-fbd3b55d1140

https://github.com/maybe-finance/marketing/assets/62795688/013fb1f7-8461-4d6f-b15f-bd88938ea688

/claim #60
/closes #60

### CODE REVIEW

**Comment by Shpigford** [comment]
Thanks so much for this! Likely will be Monday sometime before approving just because we need to dig a bit more into the calculations.

**Comment by Shpigford** [comment]
Looking fantastic! A few bits of feedback...

1. The dot (which = desired home price) needs to be shown
2. The dot plus dashed line should always be present (even when no hover state).

CleanShot 2024-06-19 at 08 34 08@2x

**Comment by neo773** [comment]
@Shpigford 

https://github.com/maybe-finance/marketing/assets/62795688/4e3d1c83-f6d5-4923-b5e1-2523e87704d3



https://github.com/maybe-finance/marketing/assets/62795688/18cd162e-5c42-4c4d-970c-8458d10bb7f7

**Comment by Shpigford** [comment]
@neo773 Thanks! The blue dot should stay fixed. It shows your "desired home price" on the spectrum

In this particular example of $320, the graph would need to extend vertically to place the blue dot at the $320k mark and the red would extend up past it a bit.

**Comment by Shpigford** [comment]
@neo773 While I'm digging through this, would you mind resolving merge conflicts?

**Pull request merged**
