### PR TITLE
Create reusable newsletter signup component

### LINKED ISSUE #1: Create a reusable newsletter signup component
Home

## Feature Overview
There is a small form object that I'd like to be able to drop in throughout the app that ultimately puts folks on a newsletter list for our upcoming beta.

## Requirements
- [ ] Style the form to match the design ([Figma file](https://www.figma.com/file/SpxlSaZ691rnkKI7CdHHnB/Marketing-Site?type=design&node-id=33%3A11154&mode=dev))
- [ ] Create a new controller/method endpoint for the form to submit to
- [ ] Should use Hotwire/Turbo/Stimulus as needed to show a success message in place of the form on submission
- [ ] The controller doesn't need to process the email address (I'll handle making an API call to ConvertKit to actually save the email address)
- [ ] The form itself should be easily dropped in to any view (sometimes multiple times in the same view, such as header and footer)

## Bounty
There is a $200 bounty on this. To participate in the bounty:

1. Comment `/attempt #1` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #1` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### PR DESCRIPTION
**Pull request by JoshAntBrown**
/claim #1
Resolves #1 

This PR adds a SignupsController, a set of views, and a helper to render a signup form anywhere within the website.

It uses a turboframe to constrain the form and it's interaction within the component.

The controller can be updated later to handle the logic of actually adding the email to the email list.

Screenshot 2024-04-29 at 16 13 29
Screenshot 2024-04-29 at 16 13 36

### CODE REVIEW

**Comment by Shpigford** [comment]
@JoshAntBrown Looks good! Mind fixing the linter error? Then I'll merge.

**Comment by JoshAntBrown** [comment]
Ah missed that, will pick that up now!

**Comment by Shpigford** [comment]
> Ah missed that, will pick that up now!

Looks like a couple more. 🙂

**Comment by JoshAntBrown** [comment]
😅 So there was, looks like I've not got my editor configured properly for this project yet. Should be all sorted now!

**Comment by JoshAntBrown** [comment]
Just pushed a small refactor to how the component gets centered, felt like it makes more sense to have the parent dictate things like max width and margins rather than trying to handle it all within the component itself.

This should be all good now.

**Pull request merged**
