### PR TITLE
Add financial freedom calculator tool

### LINKED ISSUE #35: Build Financial Freedom Calculator
Home

Home Data

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. The first one is a "Financial Freedom Calculator" which uses your savings + expenses + growth rate to help you estimate how long you can live off of your savings.

## Requirements
- [ ] Match design elements
- [ ] Slider form elements
- [ ] Graph elements (using D3)
- [ ] Graph tooltips
- [ ] Time estimation for how much "freedom" you have with active countdown
- [ ] Empty state
- [ ] Content area below calculator area
- [ ] New route at `/tools/financial-freedom-calculator`

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

You can see how we've implemented D3 over in the main app: https://github.com/maybe-finance/maybe/blob/main/app/javascript/controllers/time_series_chart_controller.js

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Financial Freedom Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=1-4)

## Bounty
There is a $300 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #35` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #35` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### LINKED ISSUE #40: Build Tools index view
Tools Directory

CleanShot 2024-06-05 at 10 53 55@2x

## Feature Overview
This is primarily a frontend/Tailwind project, though there are a few minor Ruby/Rails bits in there. We're adding a Tools section to the marketing site and need to build out the index view.

## Requirements/Specs
- [ ] Match design elements (most of the page will use existing layouts/partials)
- [ ] Icons should use the `lucide_icon` helper
- [ ] Tool items should have a partial, but will be manually set (the tools aren't pull from the database)

## Design
Here's the [Figma file](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=5104-9229).

## Bounty
There is a $100 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #40` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #40` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### PR DESCRIPTION
**Pull request by JoshAntBrown**
/claim #35
/claim #40

This PR implements the Tools index view, and the Financial Freedom Calculator.

**Demo:**

https://github.com/maybe-finance/marketing/assets/1793797/6e17f024-09b2-424b-8a5b-fce9311c89e3

Content about the tool is backed by the database and configured with Avo so you can setup all the tools and fill in the details from there. The actual tool itself is pulled in when the slug matches the partial in the tools directory. See render_tool in tools_helper.rb for implementation of that.

I've added two new dependencies: d3, and autonumeric.

I've added several Stimulus controllers:
- **autonumeric**: Applies the [autonumeric](https://autonumeric.org/) library to an element for automatic formatting of numbers and currencies.
- **countdown**: Ticks down years, months, days, hours, minutes, and seconds from a given value
- **range-input**: Used to apply custom styling to the range/slider input. Tracks the percentage fill of the bar and makes it available for CSS to style.
- **synchronized-input**: Links two or more inputs together and updates them all to have the same value whenever one of them changes.
- **time-series-bar-chart**: Renders a bar chart of a given dataset and series config
- **financial-freedom-calculator**: Performs the actual calculation and renders the given template as a result

Resolves #35 
Resolves #40

### CODE REVIEW

**Comment by JoshAntBrown** [comment]
/livestream

[**Click here to watch JoshAntBrown**](https://tv.algora.io/gh/1793797/channel)

<a id="algora-livestream" href="https://tv.algora.io/gh/1793797/channel">Watch JoshAntBrown on Algora TV</a>
[**Click here to watch JoshAntBrown**](https://tv.algora.io/gh/1793797/channel)

**Comment by JoshAntBrown** [comment]
/livestream

<a id="algora-livestream" href="https://tv.algora.io/gh/1793797/channel">Watch JoshAntBrown on Algora TV</a>
[**Click here to watch JoshAntBrown**](https://tv.algora.io/gh/1793797/channel)

**Comment by syedbarimanjan** [comment]
@Shpigford can you merge this into main I have built the roi calculator based on this branch so i can resolve any conflicts which arise and raise a pr. Thanks.

**Pull request merged**
