### PR TITLE
Fix: stock search in mini-tool

### LINKED ISSUE #178: Fix stock search in mini-tool
In our [Stock Portfolio Backtest mini-tool](https://maybe.co/tools/stock-portfolio-backtest), there are multiple fields where you can search for a stock by symbol or name.

The form is provided with JSON of all available stocks, however the sorting on it doesn't work well at all (and the javascript function that was written to do sorting doesn't work at all).

Would love to have someone fix this so that searching much more reliably returns the stocks you'd expect.

For example, trying typing in "AAPL"...you'll get lots of stocks/etfs with that string, but actually you don't get the specific "AAPL" stock. Similar issue with "META".

Relevant files:
* https://github.com/maybe-finance/marketing/blob/main/app/javascript/controllers/search_select_controller.js
* https://github.com/maybe-finance/marketing/blob/main/app/views/tools/widgets/forms/_stock_portfolio_backtest.html.erb
* https://github.com/maybe-finance/marketing/blob/main/app/views/shared/_stocks_allocator.html.erb

## Bounty
There is a $250 bounty on this.

To participate in the bounty:

1. Comment `/attempt #178` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #178` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

### PR DESCRIPTION
**Pull request by neo773**
https://github.com/user-attachments/assets/6a59d2dd-a108-478e-80a7-96f7648871fb

This PR fixes stock allocator search, the function was never being in search controller used and the filter function had some issues too.

Also added Fuse.js for fault tolerance i.e spelling mistakes.

/claim #178
/closes #178

### CODE REVIEW

**Comment by Shpigford** [comment]
I'm hesitant to add a new dependency just for this. Thoughts on a solution that doesn't involve Fuse?

**Comment by neo773** [comment]
> I'm hesitant to add a new dependency just for this. Thoughts on a solution that doesn't involve Fuse?

Sort of works, subtle spelling mistakes make it show no matches.
Fuse.js is pretty battle tested and well maintained library for it.

**Comment by neo773** [comment]
Library is also extremely lightweight at 5.1KB gzipped

image

**Comment by Shpigford** [comment]
Let's remove Fuse for now. Want to aggressively avoid dependency-creep when possible.

**Comment by neo773** [comment]
done

**Comment by Shpigford** [comment]
Thanks for the attempt on this, @neo773! We decided to use a different solution.

**Pull request closed without merging**
