### PR TITLE
Build out Article index and show views

### LINKED ISSUE #8: Build out Article index and show views
Blog Page
Blog

## Feature Overview
This is primarily a frontend/Tailwind project, though there are a few minor Ruby/Rails bits in there. We're adding an Articles section to the marketing site and need to build out the index view and single article "show" views.

## Requirements
- [ ] Match design elements
- [ ] The "gradient" headers should be randomly generated using Tailwind gradients. Ideally would have an array of colors it chooses from so we have some control there.
- [ ] Author avatar should be an if statement based on the author name
- [ ] The "Join waitlist" form should use the existing `render_signup_form`
- [ ] Read time can likely be a helper method that just measures article length and then converts that to "minutes" to read

## Design
Here's the [Figma file](https://www.figma.com/file/SpxlSaZ691rnkKI7CdHHnB/Marketing-Site?type=design&node-id=2%3A5&mode=dev).

## Bounty
There is a $350 bounty on this. To participate in the bounty:

1. Comment `/attempt #8` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #8` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### PR DESCRIPTION
**Pull request by syedbarimanjan**
fixes #8 
/claim #8

https://github.com/maybe-finance/marketing/assets/112156147/75ad8caa-84bb-4067-a0e9-a9a783354d90

 ## Requirements
 * [x]  Match design elements
 * [x]  The "gradient" headers should be randomly generated using Tailwind gradients. Ideally would have an array of colors it chooses from so we have some control there.
 * [x]  Author avatar should be an if statement based on the author name
 * [x]  The "Join waitlist" form should use the existing `render_signup_form`
 * [x]  Read time can likely be a helper method that just measures article length and then converts that to "minutes" to read

I am working on the design and then will refactor it.

### CODE REVIEW

**Comment by syedbarimanjan** [comment]
@Shpigford  can you take a look.thanks

**Comment by syedbarimanjan** [comment]
@Shpigford reminder to take a look and approve the workflow.thanks

**Comment by Shpigford** [comment]
I appreciate your work on this! Ultimately decided to go with #10 due to overall simpler code solutions across the board.

**Pull request closed without merging**
