### PR TITLE
Feat compound interest

### PR DESCRIPTION
**Pull request by LEstradioto**
/claim #44 

- Now added gradient colors
- The static values on controller
- Design is looking better

### CODE REVIEW

**Comment by Shpigford** [comment]
@LEstradioto Looking good! A few bits of feedback...

CleanShot 2024-06-08 at 11 05 05@2x

- [ ] The bottom labels should be "Year 1" and "Year X (the last year in the # of growth years"
- [ ] Tooltip should be fixed to the points on the graph, not the mouse
- [ ] Starting point for the lines on the graph should be the "0" mark
- [ ] Font weight for total value is too heavy

**Comment by LEstradioto** [comment]
Ok. All done.
Since you need mark $0, then is Year 0 to Year N.
I've adjusted the calculations too, now the calculator is good. And the interest rate is calculated monthly.

Thanks for feedback!

**Comment by Shpigford** [comment]
CleanShot 2024-06-09 at 08 53 23@2x

@LEstradioto Almost there! One last fix. The tooltips should match the year count (Year 1/2/3/4/etc) instead of being an actual date.

After that, this should be good to go!

**Comment by LEstradioto** [comment]
Done. Sorry making you work! 😅

**Comment by Shpigford** [comment]
Fantastic! Looks great. Thanks so much for your work on this!

**Pull request merged**
