### PR TITLE
feat: loan calculator

### LINKED ISSUE #43: Build Loan Calculator
Home-1
Home

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. This issue is for our "Loan Calculator" which calculates details of loan repayment.

## Requirements
- [ ] Match design elements
- [ ] Drop down form element (for days/weeks/years on loan)
- [ ] Empty state
- [ ] Calculate loan details
- [ ] Content area below calculator area

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Loan Calculator Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5093-11702&m=dev)

## Bounty
There is a $200 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #43` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #43` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### PR DESCRIPTION
**Pull request by neo773**
https://github.com/maybe-finance/marketing/assets/62795688/52cad21f-1842-4ee2-958a-b6974fae3134

/claim #43
/close #43

### CODE REVIEW

**Comment by Shpigford** [comment]
@neo773 Great job on this!

Can you make sure these numbers are formatted with commas at the appropriate thousands places?

CleanShot 2024-06-06 at 17 12 07@2x

**Comment by neo773** [comment]
@Shpigford 
Pushed!

**Comment by Shpigford** [comment]
Amazing. Great job on this, @neo773!

**Pull request merged**
