### PR TITLE
feat: boggleheads growth calculator

### LINKED ISSUE #66: Build Bogleheads Calculator
bogleheads_percentage_empty
bogleheads_percentage_filled
bogleheads_percentage_tooltips

## Feature Overview
This issue is for our "Bogleheads Growth Calculator" which is a backtesters with a mix of certain stock types. This will be added as a [free mini-tool on Maybe](https://maybe.co/tools).

## Requirements
- [ ] Match design elements
- [ ] Graph of historical returns for each stock + total returns (today - 20 years)
- [ ] Dropdowns of pre-picked stocks for each stock type (see list below)
- [ ] Locking mechanism (all 3 stocks must always add up to 100%, the lock lets you freeze a particular one to keep its % while you adjust the others)
- [ ] Risk Level indicator
- [ ] Empty state

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools
Relevant Stimulus/Javascript code: https://github.com/maybe-finance/marketing/tree/main/app/javascript/controllers
You can see how we built this tool for the previous marketing site: https://github.com/maybe-finance/marketing-archive/tree/main/app/javascript/tools/bogleheads-growth-calculator

#### Total Stock Market
* VTI (Vanguard)
* SCHB (Schwab)
* SPTM (SPDR)
* ITOT (iShares)

#### Total International Stock Market
* VXUS (Vanguard)
* SCHF (Schwab)
* SPDW (SPDR)
* IXUS (iShares)

#### Total Bond Market
* BND (Vanguard)
* SCHZ (Schwab)
* SPAB (SPDR)
* AGG (iShares)

### Stock data
You'll pull historical stock data from Synth, which has [a free plan for up to 1000 calls](https://synthfinance.com/).

The [Open/Close endpoint](https://docs.synthfinance.com/reference/openclose) is where you'll pull data for each stock.
Ex. https://api.synthfinance.com/tickers/vti/open-close?start_date=2004-06-20

These rates should be cached daily using Rails caching conventions (we use Redis in production for these types of caches, FWIW).

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Bogleheads Calculator Figma Frame](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5962-2631&m=dev)

## Bounty
There is a $350 bounty on this.

To participate in the bounty:

1. Comment `/attempt #66` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #66` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

### PR DESCRIPTION
**Pull request by jemiluv8**
fixes #66
/claim #66

## Data Requirement
The price data for computing market value of over a number of years for chosen tickers

## Data Requirement Approach
To calculate the annual market value of shares, we needed the price of the stock at the end of the year.
For years before the current one, this data doesn't change and hence I went with this approach

1. Generate seed data of end of year closing stock prices over the past 20 years for chosen tickers
2. Store seed data in a stock_prices table with colums - year, ticker, price (being the stock price at the end of that year) 
3. Create a rake task to update stock prices daily for the current year.

## Testing
Just run db:seed and you're good to go.
Also need to setup SYNTH_API_KEY - for daily current year stock price update

## Requirements Status
- [X]  Match design elements - 95%
- [X]  Dropdowns of pre-picked stocks for each stock type (see list below)
- [X]  Empty state
- [X]   Locking mechanism (all 3 stocks must always add up to 100%, the lock lets you freeze a particular one to keep its % while you adjust the others)
- [X]  Graph of historical returns for each stock + total returns (today - 20 years) - pending manual verification based on reference react implementation
- [X]  Risk Level indicator
- [X] Refactor
- [X] Self Review
- [X] Implement Own Data flow

Screenshot 2024-06-28 at 1 49 59 AM

## Demo So far - Last Updated 26/6 11:59

https://github.com/maybe-finance/marketing/assets/119384208/386f58c2-aa8b-4618-938b-3e37dfca94d4

### CODE REVIEW

**Comment by jemiluv8** [comment]
```ts
cachedAssetDtos[symbol] = axios(
    `/api/equity_prices/${symbol}?interval=month`
).then((data) => (cachedAssetDtos[symbol] = data.data));
```

@Shpigford, I've started working on the stock "data-fetching" aspect of the calculator.
Looking at the reference "react" based implementation above, I've seen we are fetching 
data over a monthly interval. The current synthfinance api you want to use doesn't seem
to have support for querying over an interval just yet. It returns using a daily interval.

I looked up the synth api documentation and even tried passing an interval query param but
I am led to believe it doesn't support querying over an interval.

This is not a blocker yet because I am proceeding to use the data data as is but within a limited time period.

Twelve data though currently supports querying over an interval so perhaps we could consider it as well even though
I know synthfinance is under your control so you'd prefer that.

**Comment by Shpigford** [comment]
> ```ts
> cachedAssetDtos[symbol] = axios(
>     `/api/equity_prices/${symbol}?interval=month`
> ).then((data) => (cachedAssetDtos[symbol] = data.data));
> ```
> 
> @Shpigford, I've started working on the stock "data-fetching" aspect of the calculator. Looking at the reference "react" based implementation above, I've seen we are fetching data over a monthly interval. The current synthfinance api you want to use doesn't seem to have support for querying over an interval just yet. It returns using a daily interval.
> 
> I looked up the synth api documentation and even tried passing an interval query param but I am led to believe it doesn't support querying over an interval.
> 
> This is not a blocker yet because I am proceeding to use the data data as is but within a limited time period.
> 
> Twelve data though currently supports querying over an interval so perhaps we could consider it as well even though I know synthfinance is under your control so you'd prefer that.

@jemiluv8 Looking great! I can add the monthly interval to the Synth API if that'd be helpful. Just let me know and I'll get it built out in the next ~24 hours.

**Comment by jemiluv8** [comment]
I do have some updates regarding the data fetching for the calculations.

**Comment by jemiluv8** [comment]
I've created a table to store annual closing stock prices
This data is fetched and made available to the view.

So we don't do any data fetching on the client side. It just uses 
static information made available to the view.

I've a rake task to update current year's price on a daily basis

### The downside of my approach is that
1. Original share price is based on the earliest year data not the earliest month data used in the reference implementation
2. The downside deviation and related data are based on annual instead of monthly data.

### On the upside
1. There is no data fetching on the client side since it has data on our supported stocks
2. It is faster to just setup - with the seeded stock_prices

My key concerns here are 
1. Stock prices will differ if we use the earliest date - in months - instead of the annual closing figure.
2. The downside deviation will also differ from the reference implementation

**Comment by Shpigford** [comment]
@jemiluv8 Would it be a major change to just change the data to use monthly instead of annual? It'd obviously be *more* data but still not an absurd amount of data.

**Comment by jemiluv8** [comment]
It won't be a major change. 
I suppose you want us to plot the monthly value of the share prices as well?

**Comment by Shpigford** [comment]
> I suppose you want us to plot the monthly value of the share prices as well?

Ideally, yes.

**Comment by jemiluv8** [comment]
Ok. got it. 
So you're ok with the current data flow I've proposed.
With the stock prices table and all.

So the only update will be that I'll use end of month stock price for each month that is stored.
Everything will be maintained as is.

**Comment by Shpigford** [comment]
@jemiluv8 Yep, works for me for where we're today at with all of these mini-tools. 🙂

**Comment by jemiluv8** [comment]
And of course, from the reference implementation, even though we intend to plot data over the past 20years,
some stocks don't have data going that far back. So I ended up starting the graph data from the least common date.

But I still computed the shares based on the earliest date for each stock. Is that sound?

**Comment by Shpigford** [comment]
@jemiluv8 You'd want to compute based on least common date for all the *chosen* stocks.

So if Stock A goes back to 2002 but Stock B only goes back to 2015, then you'd calculate all based on 2015 start date.

**Comment by jemiluv8** [comment]
Ok. So the least common date is assumed to be the date the portfolio started. 
Makes sense.

**Comment by jemiluv8** [comment]
Will start making changes and revert

**Comment by jemiluv8** [comment]
I've made changes to plot graph based on monthly closing stock price.
All other computations like risk, returns, downside deviation have
been updated as required.

I've been reading about setting up the whenever gem to help us schedule
cron jobs for the daily stock price update - I'll create a new issue for now.

Let me know how your click-testing goes.

**Comment by Shpigford** [comment]
@jemiluv8 Great job on this! Only bit of feedback I've got is on the lock mechanism.

https://github.com/maybe-finance/marketing/assets/35243/233ddb95-c6bb-4b65-a45e-d763b18c573b

**Comment by jemiluv8** [comment]
Ok. The video clarifies the intent of the locking mechanism
I'll work on it and revert.

Glad it tested out ok.

**Comment by jemiluv8** [comment]
I have updated the workings of the locking mechanism to work as you demonstrated in your video.
Only corner case I discovered was that when let's say slide A is disabled, slide C can be moved up to
100% in which case, I go ahead and modify slide A even though it is locked. 

## DEMO 1
https://github.com/maybe-finance/marketing/assets/119384208/39d340f8-fa39-4dd9-ab84-6c3f55ce4300


## DEMO 2
https://github.com/maybe-finance/marketing/assets/119384208/f9d88571-1d68-475c-aa72-01ccedbfba1f

**Comment by Shpigford** [comment]
Getting NaN in testing. (I ran `StockPrice.update_stock_prices`, FWIW)

CleanShot 2024-07-02 at 09 39 51@2x

CleanShot 2024-07-02 at 09 40 27@2x

**Comment by jemiluv8** [comment]
I'll try replicating that here

**Comment by jemiluv8** [comment]
How's the locking mechanism?

**Comment by Shpigford** [comment]
> How's the locking mechanism?

It's perfect!

**Comment by jemiluv8** [comment]
Has to do with not having stock data for July.
You need to run
`
./bin/rake data:update_stock_prices
`

and flush redis entire or just the key "stock_prices"

**Comment by jemiluv8** [comment]
I'll update it to ensure it works well with available data regardless

**Comment by Shpigford** [comment]
While you're working on those fixes, one small chart bit. The top dot is getting cut off.

CleanShot 2024-07-02 at 10 15 06@2x

**Comment by jemiluv8** [comment]
I just fixed the drop off and made the bugfix to use data up to the current month

Screenshot 2024-07-02 at 3 25 03 PM

**Comment by Shpigford** [comment]
@jemiluv8 Nitpick, but there's still a tiny cut-off on that top pink circle. 🫣

**Comment by jemiluv8** [comment]
Fixed the nit.

Screenshot 2024-07-02 at 3 50 24 PM

**Comment by Shpigford** [comment]
@jemiluv8 Fantastic. Just to make sure I'm clear, `data:update_stock_prices` rake task should be run daily...is that right?

**Comment by jemiluv8** [comment]
Yes please.

**Pull request merged**
